#!/bin/bash
trap 'echo received signal, quitting...; exit 1' INT TERM
set -xe

bgrun() {
eatmydata "$@" &
wait "$!"
}

if [ -d /localrepo/dists ]
then
	echo "deb [trusted=yes] file:///localrepo/ ${DIST_CODENAME} main" > /etc/apt/sources.list.d/local.list
fi

bgrun apt-get -y update
bgrun dpkg -R --unpack /deps
bgrun apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends --fix-broken install

mkdir -p /tmp/src
bgrun tar -C /tmp/src -xf /src/*.orig.tar.*
cd /tmp/src/*
cp -a /src/debian .
cp /src/*.orig.tar.* /tmp/src
bgrun dpkg-buildpackage "$@"

chown -R $(stat -c '%u:%g' /src) /tmp/src
find /tmp/src -type f -execdir mv -t /src -- '{}' '+'
