#!/bin/bash
set -x

trap 'echo received signal, quitting...; exit 1' INT TERM

apt-get -y update || exit 1
dpkg -R --unpack /deps
apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends --fix-broken install
dpkg -R --unpack /deps
apt-get -t "${DIST_CODENAME}-backports" -o Debug::pkgProblemResolver=yes -y --no-install-recommends --fix-broken install
dpkg -R --unpack /deps
cat<<EOF > /etc/apt/preferences.d/zzz_priority
Package: *
Pin: release a=*
Pin-Priority:500
EOF
apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends --fix-broken install
dpkg -R --install /deps || exit 1

mkdir /tmp/src
cp -r /src/* /tmp/src
cd /tmp/src || exit 1
cd "$(find . -mindepth 1 -maxdepth 1 -type d || exit 1)" || exit 1
dpkg-buildpackage "$@" || exit 1

cd /tmp/src || exit 1
rm -rf "$(find . -mindepth 1 -maxdepth 1 -type d || exit 1)" || exit 1
chown -R $(stat -c '%u:%g' /src) *
mv -t /src -- *
