#!/bin/bash
trap 'echo received signal, quitting...; exit 1' INT TERM
set -xe

bgrun() {
"$@" &
wait "$!"
}

if [ -d /localrepo/repodata ]
then
cat<<EOF > /tmp/localrepo.repo
[localrepo]
name=localrepo
type=rpm-md
baseurl=file:///localrepo/
gpgcheck=0
enabled=1
EOF
dnf config-manager --add-repo /tmp/localrepo.repo || true
fi

bgrun dnf upgrade -y || bgrun yum upgrade -y

bgrun dnf builddep -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False --best /src/*.spec

# debug
ls -l        /etc/profile.d/00-modulepath.sh && echo YEA || echo NAY >&2
test -r      /etc/profile.d/00-modulepath.sh && echo YEA || echo NAY >&2
/bin/test -r /etc/profile.d/00-modulepath.sh && echo YEA || echo NAY >&2
ls -l        /etc/profile.d/modules.sh && echo YEA || echo NAY >&2
test -r      /etc/profile.d/modules.sh && echo YEA || echo NAY >&2
/bin/test -r /etc/profile.d/modules.sh && echo YEA || echo NAY >&2
ls -l        /etc/alternatives/modules.sh && echo YEA || echo NAY >&2
test -r      /etc/alternatives/modules.sh && echo YEA || echo NAY >&2
/bin/test -r /etc/alternatives/modules.sh && echo YEA || echo NAY >&2
ls -l        /usr/share/lmod/lmod/init/profile && echo YEA || echo NAY >&2
test -r      /usr/share/lmod/lmod/init/profile && echo YEA || echo NAY >&2
/bin/test -r /usr/share/lmod/lmod/init/profile && echo YEA || echo NAY >&2

# re-read profile after installation to load any new env
set +e
. /etc/profile
set -e

# debug
module || echo NOPE >&2

mkdir -p "/tmp/BUILD" "/tmp/output" "/tmp/output/src"
bgrun rpmbuild \
	--define "_topdir    /tmp" \
	--define "_builddir  %{_topdir}/BUILD" \
	--define "_rpmdir    %{_topdir}/output" \
	--define "_sourcedir /src" \
	--define "_specdir   /src" \
	--define "_srcrpmdir %{_topdir}/output/src" \
	--define "_tmppath   tmp" \
	--undefine=_disable_source_fetch \
	-ba /src/*.spec
chown -R $(stat -c '%u:%g' /src) /tmp/output
find /tmp/output -type f -name '*.rpm' -execdir mv -t /src -- '{}' '+'
