#!/bin/bash
trap 'echo received signal, quitting...; exit 1' INT TERM
set -xe

test -e /usr/lib64/nosync/nosync.so && export LD_PRELOAD="/usr/lib64/nosync/nosync.so"

bgrun() {
"$@" &
wait "$!"
}

cat<<EOF > /tmp/localrepo.repo
[localrepo]
name=localrepo
type=rpm-md
baseurl=file:///localrepo/
gpgcheck=0
enabled=1
EOF
dnf config-manager --add-repo /tmp/localrepo.repo || true

bgrun dnf builddep -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False --best /src/*.spec

mkdir -p "/tmp/BUILD" "/tmp/output" "/tmp/SOURCES" "/tmp/output/src"
bgrun bash -lc 'rpmbuild \
	--define "_topdir    /tmp" \
	--define "_builddir  %{_topdir}/BUILD" \
	--define "_rpmdir    %{_topdir}/output" \
	--define "_sourcedir %{_topdir}/SOURCES" \
	--define "_specdir   /src" \
	--define "_srcrpmdir %{_topdir}/output/src" \
	--define "_tmppath   tmp" \
	--undefine=_disable_source_fetch \
	-ba /src/*.spec'
chown -R $(stat -c '%u:%g' /src) /tmp/output
find /tmp/output -type f -name '*.rpm' -execdir mv -t /src -- '{}' '+'
